name: Continuous Integration (CI)

on:
  push:
    branches:
      # We can define multiple branches as well
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install package dependencies
        run: yarn

        # Custom script for creating the test build
      - name: Create test build
        run: yarn build

